name: tf-checks

on:
  pull_request:
  workflow_dispatch:

jobs:
# Update 'Job name' and 'working_directory' as needed based on the module structure.
  complete-example:
    uses: clouddrove/github-shared-workflows/.github/workflows/stf-checks.yml@v2
    with:
      working_directory: './examples/complete/'
      provider: none

  managed-rule-overrides-example:
    uses: clouddrove/github-shared-workflows/.github/workflows/stf-checks.yml@v2
    with:
      working_directory: './examples/managed-rule-overrides/'
      provider: none

# Seperate Job for TFlint workflow call
  tf-lint:
    uses: clouddrove/github-shared-workflows/.github/workflows/tf-lint.yml@v2
    secrets:
      GITHUB: ${{ secrets.GITHUB }}